// productos.js - Inventario actualizado AME FIGURES (VERSIÓN SEO OPTIMIZADA)
// Categorías unificadas para mejor indexación en Google

const productos = [
    // ============================================
    // DRAGON BALL (UNIFICADO)
    // ============================================
    {
        id: 'DB_FIG_001',
        sku: 'DB_FIG_001',
        nombre: 'Dragon Ball - Son Goku Super Saiyan',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura coleccionable de Son Goku Super Saiyan de Dragon Ball - 18 cm. Perfecta para fans de la serie, con acabados de alta calidad y pose dinámica.',
        palabrasClave: 'Dragon Ball, Goku, Super Saiyan, figura coleccionable, anime, figura Goku Dragon Ball, colección anime Perú',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874449/DB_FIG_001.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_001_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_001_2.png'
    },
    {
        id: 'DB_FIG_002',
        sku: 'DB_FIG_002',
        nombre: 'Dragon Ball - Vegito Super Saiyan Blue',
        tamaño: '11 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura coleccionable de Vegito Super Saiyan Blue de Dragon Ball - 11 cm. La fusión definitiva en formato figura de alta calidad.',
        palabrasClave: 'Dragon Ball, Vegito, Super Saiyan Blue, figura, colección, Vegito Dragon Ball, fusión',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_002.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_002_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_002_2.png'
    },
    {
        id: 'DB_FIG_003',
        sku: 'DB_FIG_003',
        nombre: 'Dragon Ball - Escena Goku Cazando Pescado',
        tamaño: '6.5 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura escena de Goku cazando pescado de Dragon Ball - 6.5 cm. Escena icónica del entrenamiento de Goku en la naturaleza.',
        palabrasClave: 'Dragon Ball, Goku, escena, pescando, figura mini, Goku pescando, escena Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_003.png'
    },
    {
        id: 'DB_FIG_004',
        sku: 'DB_FIG_004',
        nombre: 'Dragon Ball - Trunks',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 50,
        precioInflado: 58.50,
        descripcion: 'Figura coleccionable de Trunks de Dragon Ball - 19 cm. El guerrero del futuro en formato figura de acción detallada.',
        palabrasClave: 'Dragon Ball, Trunks, figura de acción, coleccionable, Trunks del futuro, espada',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_004.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_004_1.png'
    },
    {
        id: 'DB_FIG_005',
        sku: 'DB_FIG_005',
        nombre: 'Dragon Ball - Vegeta y Freezer',
        tamaño: '10.5 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Figura de Vegeta y Freezer de Dragon Ball - 10.5 cm. Dupla de dos de los personajes más poderosos del universo Dragon Ball.',
        palabrasClave: 'Dragon Ball, Vegeta, Freezer, dupla, figura, Vegeta y Freezer, enemigos',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_005.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874406/DB_FIG_005_1.png'
    },
    {
        id: 'DB_FIG_006',
        sku: 'DB_FIG_006',
        nombre: 'Dragon Ball - Goku con Báculos',
        tamaño: '20 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Figura de Goku con báculos de Dragon Ball - 20 cm. Figura articulada con el icónico báculo del Guerrero Saiyan.',
        palabrasClave: 'Dragon Ball, Goku, báculo, figura articulada, Goku báculo sagrado',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_006.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_006_1.png'
    },
    {
        id: 'DB_FIG_007',
        sku: 'DB_FIG_007',
        nombre: 'Dragon Ball - Androide N° 17',
        tamaño: '24 cm',
        precioOferta: 45,
        descuento: 40,
        precioInflado: 63.00,
        descripcion: 'Figura de Androide N° 17 de Dragon Ball - 24 cm. Figura tamaño grande del guardián de la naturaleza y luchador poderoso.',
        palabrasClave: 'Dragon Ball, Androide 17, figura grande, colección, Androide 17 Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_007.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_007_1.png'
    },
    {
        id: 'DB_FIG_008',
        sku: 'DB_FIG_008',
        nombre: 'Dragon Ball - Androide N° 18',
        tamaño: '23 cm',
        precioOferta: 45,
        descuento: 50,
        precioInflado: 67.50,
        descripcion: 'Figura de Androide N° 18 de Dragon Ball - 23 cm. Figura femenina de alta calidad, esposa de Krilin y poderosa guerrera.',
        palabrasClave: 'Dragon Ball, Androide 18, figura femenina, coleccionable, Androide 18 Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008_2.png'
    },
    {
        id: 'DB_FIG_009',
        sku: 'DB_FIG_009',
        nombre: 'Dragon Ball - Bulma',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Bulma de Dragon Ball - 18 cm. La científica más inteligente del universo en formato figura coleccionable.',
        palabrasClave: 'Dragon Ball, Bulma, figura, anime, Bulma Dragon Ball, científica',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_009.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_009_1.png '
    },
    {
        id: 'DB_FIG_010',
        sku: 'DB_FIG_010',
        nombre: 'Dragon Ball - Maestro Roshi',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 20,
        precioInflado: 36.00,
        descripcion: 'Figura de Maestro Roshi de Dragon Ball - 10 cm. El maestro de las artes marciales y creador de la Kame Hame Ha.',
        palabrasClave: 'Dragon Ball, Roshi, maestro, figura, Maestro Roshi, Kame Hame Ha',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_010.png'
    },
    {
        id: 'DB_FIG_011',
        sku: 'DB_FIG_011',
        nombre: 'Dragon Ball - Trunks del Futuro Super Saiyan Dai-San Dankai',
        tamaño: '27 cm',
        precioOferta: 55,
        descuento: 30,
        precioInflado: 71.50,
        descripcion: 'Figura de Trunks del Futuro Super Saiyan de Dragon Ball - 27 cm. Figura tamaño gigante del guerrero que vino del futuro.',
        palabrasClave: 'Dragon Ball, Trunks del Futuro, Super Saiyan, figura grande, Trunks futuro, Dai-San Dankai',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011_2.png'
    },
    {
        id: 'DB_FIG_012',
        sku: 'DB_FIG_012',
        nombre: 'Dragon Ball - Krilin',
        tamaño: '16.5 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Krilin de Dragon Ball - 16.5 cm. El mejor amigo de Goku y el humano más fuerte del universo.',
        palabrasClave: 'Dragon Ball, Krilin, figura, coleccionable, Krilin Dragon Ball, humano más fuerte',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_012.png'
    },
    {
        id: 'DB_FIG_013',
        sku: 'DB_FIG_013',
        nombre: 'Dragon Ball - Arale',
        tamaño: '15 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Arale de Dragon Ball - 15 cm. La crossover más divertida, la androide de Dr. Slump.',
        palabrasClave: 'Dragon Ball, Arale, figura, crossover, Arale Dragon Ball, Dr Slump',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_013.png'
    },
    {
        id: 'DB_FIG_014',
        sku: 'DB_FIG_014',
        nombre: 'Dragon Ball - Golden Freezer',
        tamaño: '28 cm',
        precioOferta: 55,
        descuento: 20,
        precioInflado: 66.00,
        descripcion: 'Figura de Golden Freezer de Dragon Ball - 28 cm. La transformación dorada del emperador del universo.',
        palabrasClave: 'Dragon Ball, Golden Freezer, figura, tamaño grande, Freezer dorado, emperador',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_014.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_014_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_014_2.png'
    },
    {
        id: 'DB_FIG_015',
        sku: 'DB_FIG_015',
        nombre: 'Dragon Ball - Freezer',
        tamaño: '28 cm',
        precioOferta: 55,
        descuento: 30,
        precioInflado: 71.50,
        descripcion: 'Figura de Freezer de Dragon Ball - 28 cm. El temido emperador del universo en su forma final.',
        palabrasClave: 'Dragon Ball, Freezer, figura, colección, Freezer forma final, emperador del universo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_015.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_015_1.png'
    },
    {
        id: 'DB_SET_016',
        sku: 'DB_SET_016',
        nombre: 'Dragon Ball - Set Goku Comiendo',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set coleccionable de Goku comiendo de Dragon Ball - 10 cm. Incluye accesorios y figura de Goku disfrutando de su comida.',
        palabrasClave: 'Dragon Ball, Goku, comiendo, set, figura, colección Dragon Ball, Goku comiendo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874325/DB_SET_016.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_016_1.png'
    },
    {
        id: 'DB_SET_017',
        sku: 'DB_SET_017',
        nombre: 'Dragon Ball - Set Vegeta Comiendo',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Set coleccionable de Vegeta comiendo de Dragon Ball - 10 cm. El príncipe Saiyan disfrutando de su comida.',
        palabrasClave: 'Dragon Ball, Vegeta, comiendo, set, figura, Vegeta comiendo, colección Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_017.png'
    },
    {
        id: 'DB_SET_018',
        sku: 'DB_SET_018',
        nombre: 'Dragon Ball - Set Gohan Comiendo',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Set coleccionable de Gohan comiendo de Dragon Ball - 10 cm. El hijo de Goku disfrutando de su comida.',
        palabrasClave: 'Dragon Ball, Gohan, comiendo, set, figura, Gohan comiendo, colección Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_018.png'
    },
    {
        id: 'DB_SET_019',
        sku: 'DB_SET_019',
        nombre: 'Dragon Ball - Set Androide N° 18 Comiendo',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set coleccionable de Androide N° 18 comiendo de Dragon Ball - 10 cm. La guerrera androide en un momento cotidiano.',
        palabrasClave: 'Dragon Ball, Androide 18, comiendo, set, figura, Androide 18 comiendo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_019.png'
    },
    {
        id: 'DB_SET_020',
        sku: 'DB_SET_020',
        nombre: 'Dragon Ball - Set Krilin Comiendo',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set coleccionable de Krilin comiendo de Dragon Ball - 10 cm. El mejor amigo de Goku en un momento relajado.',
        palabrasClave: 'Dragon Ball, Krilin, comiendo, set, figura, Krilin comiendo, colección',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874321/DB_SET_020.png'
    },
    {
        id: 'DB_FIG_021',
        sku: 'DB_FIG_021',
        nombre: 'Dragon Ball - Majin Vegeta',
        tamaño: '21 cm',
        precioOferta: 39,
        descuento: 50,
        precioInflado: 58.50,
        descripcion: 'Figura de Majin Vegeta de Dragon Ball - 21 cm. La versión malvada del príncipe Saiyan controlado por Babidi.',
        palabrasClave: 'Dragon Ball, Majin Vegeta, figura, acción, Majin Vegeta Dragon Ball, Vegeta malvado',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_021.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874321/DB_FIG_021_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_021_2.png'
    },
    {
        id: 'DB_FIG_022',
        sku: 'DB_FIG_022',
        nombre: 'Dragon Ball - Goku Super Saiyan 1',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku Super Saiyan 1 de Dragon Ball - 16 cm. La transformación que cambió la historia del anime.',
        palabrasClave: 'Dragon Ball, Goku, Super Saiyan 1, figura, Goku SSJ, primera transformación',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_022.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_FIG_022_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_022_2.png'
    },
    {
        id: 'DB_SET_023',
        sku: 'DB_SET_023',
        nombre: 'Dragon Ball - Set de 13 Figuras',
        tamaño: '7 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 13 figuras de Dragon Ball - 7 cm cada una. Lote completo con los personajes principales de la serie.',
        palabrasClave: 'Dragon Ball, lote, 13 figuras, mini figuras, colección, set completo Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874319/DB_SET_023.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_3.png'
    },
    {
        id: 'DB_SET_024',
        sku: 'DB_SET_024',
        nombre: 'Dragon Ball - Set 8 Transformaciones de Majin Boo',
        tamaño: '8-12 cm',
        precioOferta: 59,
        descuento: 40,
        precioInflado: 82.60,
        descripcion: 'Set de 8 transformaciones de Majin Boo de Dragon Ball - 8 a 12 cm. Todas las formas del temible Majin Boo.',
        palabrasClave: 'Dragon Ball, Majin Boo, transformaciones, set, figuras, todas las formas de Boo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_024.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_3.png'
    },
    {
        id: 'DB_SET_025',
        sku: 'DB_SET_025',
        nombre: 'Dragon Ball - Set 8 Transformaciones de Freezer',
        tamaño: '8-12 cm',
        precioOferta: 59,
        descuento: 50,
        precioInflado: 88.50,
        descripcion: 'Set de 8 transformaciones de Freezer de Dragon Ball - 8 a 12 cm. Todas las formas del emperador del universo.',
        palabrasClave: 'Dragon Ball, Freezer, transformaciones, set, figuras, todas las formas de Freezer',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874316/DB_SET_025.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_025_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874316/DB_SET_025_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_025_3.png'
    },
    {
        id: 'DB_SET_026',
        sku: 'DB_SET_026',
        nombre: 'Dragon Ball - Set 5 Figuras de Boo',
        tamaño: '8 cm',
        precioOferta: 50,
        descuento: 20,
        precioInflado: 60.00,
        descripcion: 'Set de 5 figuras de Boo de Dragon Ball - 8 cm. Las versiones más icónicas del ser mágico.',
        palabrasClave: 'Dragon Ball, Boo, set, figuras, colección, Majin Boo set',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_026.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_026_1.png'
    },
    {
        id: 'DB_SET_027',
        sku: 'DB_SET_027',
        nombre: 'Dragon Ball - Set de 16 Figuras',
        tamaño: '7 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 16 figuras de Dragon Ball - 7 cm. El lote más completo con personajes de todas las sagas.',
        palabrasClave: 'Dragon Ball, lote, 16 figuras, miniaturas, set completo, colección Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_027.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_027_1.png'
    },
    {
        id: 'DB_SET_028',
        sku: 'DB_SET_028',
        nombre: 'Dragon Ball - Set de 7 Figuras',
        tamaño: '9-10 cm',
        precioOferta: 80,
        descuento: 40,
        precioInflado: 112.00,
        descripcion: 'Set de 7 figuras de Dragon Ball - 9 a 10 cm. Figuras de tamaño mediano de los guerreros Z.',
        palabrasClave: 'Dragon Ball, set, 7 figuras, tamaño mediano, guerreros Z, colección',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_028.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_028_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_028_2.png'
    },
    {
        id: 'DB_SET_029',
        sku: 'DB_SET_029',
        nombre: 'Dragon Ball - Set de 8 Figuras Variadas',
        tamaño: '6-10 cm',
        precioOferta: 50,
        descuento: 50,
        precioInflado: 75.00,
        descripcion: 'Set de 8 figuras variadas de Dragon Ball - 6 a 10 cm. Surtido de personajes de diferentes sagas.',
        palabrasClave: 'Dragon Ball, set, 8 figuras, lote, variedad, personajes Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874222/DB_SET_029.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_029_1.png'
    },
    {
        id: 'DB_FIG_030',
        sku: 'DB_FIG_030',
        nombre: 'Dragon Ball - Goku y Puar',
        tamaño: '11 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku y Puar de Dragon Ball - 11 cm. La dupla del Saiyan y su amigo transformable.',
        palabrasClave: 'Dragon Ball, Goku, Puar, dupla, figura, Goku y Puar',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874221/DB_FIG_030.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874221/DB_FIG_030_1.png'
    },
    {
        id: 'DB_FIG_031',
        sku: 'DB_FIG_031',
        nombre: 'Dragon Ball - Goku Colgando de la Nube Voladora',
        tamaño: '9 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Goku colgando de la nube voladora - 9 cm. Escena icónica del pequeño Goku viajando en Kinton.',
        palabrasClave: 'Dragon Ball, Goku, nube voladora, escena, figura, Kinton, nube mágica',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874220/DB_FIG_031.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874220/DB_FIG_031_1.png'
    },
    {
        id: 'DB_FIG_032',
        sku: 'DB_FIG_032',
        nombre: 'Dragon Ball - Goku con Báculo Sagrado',
        tamaño: '14 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Goku con báculo sagrado de Dragon Ball - 14 cm. El icónico Nyoi Bo en manos del joven Saiyan.',
        palabrasClave: 'Dragon Ball, Goku, báculo sagrado, figura, Nyoi Bo, báculo mágico',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874219/DB_FIG_032.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874220/DB_FIG_032_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874219/DB_FIG_032_2.png'
    },
    {
        id: 'DB_FIG_033',
        sku: 'DB_FIG_033',
        nombre: 'Dragon Ball - Escena Goku vs Piccolo',
        tamaño: '7.5 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura escena de Goku vs Piccolo de Dragon Ball - 7.5 cm. Diorama de la batalla en el torneo de artes marciales.',
        palabrasClave: 'Dragon Ball, Goku, Piccolo, batalla, escena, Goku vs Piccolo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874219/DB_FIG_033.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874200/DB_FIG_033_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_033_2.png'
    },
    {
        id: 'DB_FIG_034',
        sku: 'DB_FIG_034',
        nombre: 'Dragon Ball - Goku y Maestro Karin',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku y Maestro Karin de Dragon Ball - 12 cm. El guardián de la torre Karin entrenando a Goku.',
        palabrasClave: 'Dragon Ball, Goku, Karin, figura, Maestro Karin, torre Karin',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874222/DB_FIG_034.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_034_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_034_2.png'
    },
    {
        id: 'DB_FIG_035',
        sku: 'DB_FIG_035',
        nombre: 'Dragon Ball - Broly',
        tamaño: '20 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Broly de Dragon Ball - 20 cm. El Saiyan legendario en su forma más poderosa.',
        palabrasClave: 'Dragon Ball, Broly, figura, acción, Broly Saiyan legendario, Legendario Super Saiyan',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_035.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_035_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_035_2.png'
    },
    {
        id: 'DB_FIG_036',
        sku: 'DB_FIG_036',
        nombre: 'Dragon Ball - Bills (Beerus)',
        tamaño: '30 cm',
        precioOferta: 59,
        descuento: 40,
        precioInflado: 82.60,
        descripcion: 'Figura de Bills de Dragon Ball - 30 cm. El Dios de la Destrucción en tamaño gigante.',
        palabrasClave: 'Dragon Ball, Bills, dios de la destrucción, figura grande, Beerus, Bills Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036_2.png'
    },
    {
        id: 'DB_FIG_037',
        sku: 'DB_FIG_037',
        nombre: 'Dragon Ball - Shenlong',
        tamaño: '18 cm',
        precioOferta: 55,
        descuento: 50,
        precioInflado: 82.50,
        descripcion: 'Figura de Shenlong de Dragon Ball - 18 cm. El majestuoso dragón que concede deseos.',
        palabrasClave: 'Dragon Ball, Shenlong, dragón, figura, Shenlong Dragon Ball, dragón mágico',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_037_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037_3.png'
    },
    {
        id: 'DB_FIG_038',
        sku: 'DB_FIG_038',
        nombre: 'Dragon Ball - Escena Goku vs Krilin',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura escena de Goku vs Krilin de Dragon Ball - 8 cm. El entrenamiento de los mejores amigos.',
        palabrasClave: 'Dragon Ball, Goku, Krilin, pelea, escena, Goku vs Krilin, entrenamiento',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_038.png'
    },
    {
        id: 'DB_FIG_039',
        sku: 'DB_FIG_039',
        nombre: 'Dragon Ball - Maestro Roshi y Bulma',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Maestro Roshi y Bulma de Dragon Ball - 8 cm. La dupla cómica de la serie original.',
        palabrasClave: 'Dragon Ball, Roshi, Bulma, figura, Maestro Roshi y Bulma, Dragon Ball clásico',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_039.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874130/DB_FIG_039_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873916/DB_FIG_039_2.png'
    },
    {
        id: 'DB_FIG_040',
        sku: 'DB_FIG_040',
        nombre: 'Dragon Ball - Bulma (Mini)',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Bulma de Dragon Ball - 7 cm. Versión mini de la inteligente científica.',
        palabrasClave: 'Dragon Ball, Bulma, mini figura, Bulma mini, colección',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873893/DB_FIG_040.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873870/DB_FIG_040_1.png'
    },
    {
        id: 'DB_FIG_041',
        sku: 'DB_FIG_041',
        nombre: 'Dragon Ball - Escena Ozaru',
        tamaño: '7.5 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura escena de Ozaru de Dragon Ball - 7.5 cm. El mono gigante, transformación de los Saiyan.',
        palabrasClave: 'Dragon Ball, Ozaru, mono gigante, escena, gran mono, transformación Saiyan',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873825/DB_FIG_041.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_041_1.png'
    },
    {
        id: 'DB_FIG_042',
        sku: 'DB_FIG_042',
        nombre: 'Dragon Ball - Goku (Versión Básica)',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 20,
        precioInflado: 36.00,
        descripcion: 'Figura de Goku de Dragon Ball - 10 cm. Versión básica del héroe Saiyan.',
        palabrasClave: 'Dragon Ball, Goku, figura básica, Goku pequeño, colección',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_042.png,https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_042_1.png'
    },
    {
        id: 'DB_FIG_043',
        sku: 'DB_FIG_043',
        nombre: 'Dragon Ball x Pokémon - Psyduck Cell',
        tamaño: '9 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Psyduck Cell (crossover) - 9 cm. La fusión entre Dragon Ball y Pokémon.',
        palabrasClave: 'Dragon Ball, Pokémon, crossover, Psyduck, Cell, figura, fusión',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043_2.png'
    },
    {
        id: 'DB_FIG_044',
        sku: 'DB_FIG_044',
        nombre: 'Dragon Ball - Goku en Motocicleta',
        tamaño: '13 cm',
        precioOferta: 50,
        descuento: 30,
        precioInflado: 65.00,
        descripcion: 'Figura de Goku en motocicleta de Dragon Ball - 13 cm. Vehículo coleccionable con el Saiyan.',
        palabrasClave: 'Dragon Ball, Goku, motocicleta, vehículo, figura, Goku moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873812/DB_FIG_044.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873792/DB_FIG_044_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_044_2.png'
    },
    {
        id: 'DB_FIG_045',
        sku: 'DB_FIG_045',
        nombre: 'Dragon Ball - Majin Boo en Motocicleta',
        tamaño: '11 cm',
        precioOferta: 50,
        descuento: 40,
        precioInflado: 70.00,
        descripcion: 'Figura de Majin Boo en motocicleta de Dragon Ball - 11 cm. El ser mágico en un divertido vehículo.',
        palabrasClave: 'Dragon Ball, Majin Boo, motocicleta, figura, Boo moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_045.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_045_1.png'
    },
    {
        id: 'DB_FIG_046',
        sku: 'DB_FIG_046',
        nombre: 'Dragon Ball - Freezer en Motocicleta',
        tamaño: '11 cm',
        precioOferta: 50,
        descuento: 50,
        precioInflado: 75.00,
        descripcion: 'Figura de Freezer en motocicleta de Dragon Ball - 11 cm. El emperador del universo sobre ruedas.',
        palabrasClave: 'Dragon Ball, Freezer, motocicleta, figura, Freezer moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_046.png'
    },
    {
        id: 'DB_FIG_047',
        sku: 'DB_FIG_047',
        nombre: 'Dragon Ball - Cell en Motocicleta',
        tamaño: '12 cm',
        precioOferta: 50,
        descuento: 20,
        precioInflado: 60.00,
        descripcion: 'Figura de Cell en motocicleta de Dragon Ball - 12 cm. El bio-androide perfecto en vehículo.',
        palabrasClave: 'Dragon Ball, Cell, motocicleta, figura, Cell moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_047.png'
    },
    {
        id: 'DB_FIG_048',
        sku: 'DB_FIG_048',
        nombre: 'Dragon Ball - Gohan en Motocicleta',
        tamaño: '12 cm',
        precioOferta: 50,
        descuento: 30,
        precioInflado: 65.00,
        descripcion: 'Figura de Gohan en motocicleta de Dragon Ball - 12 cm. El hijo de Goku en vehículo.',
        palabrasClave: 'Dragon Ball, Gohan, motocicleta, figura, Gohan moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_048.png'
    },
    {
        id: 'DB_FIG_049',
        sku: 'DB_FIG_049',
        nombre: 'Dragon Ball - Maestro Roshi en Motocicleta',
        tamaño: '13 cm',
        precioOferta: 50,
        descuento: 40,
        precioInflado: 70.00,
        descripcion: 'Figura de Maestro Roshi en motocicleta de Dragon Ball - 13 cm. El maestro en un divertido vehículo.',
        palabrasClave: 'Dragon Ball, Roshi, motocicleta, figura, Roshi moto',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_049.png'
    },
    {
        id: 'DB_FIG_050',
        sku: 'DB_FIG_050',
        nombre: 'Dragon Ball - Goku en Nube Voladora',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Figura de Goku en nube voladora de Dragon Ball - 12 cm. El clásico Kinton del pequeño Goku.',
        palabrasClave: 'Dragon Ball, Goku, nube voladora, figura, Kinton, nube mágica',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_FIG_050.png'
    },
    {
        id: 'DB_VEH_051',
        sku: 'DB_VEH_051',
        nombre: 'Dragon Ball - Máquina del Tiempo de Bulma',
        tamaño: '8 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Vehículo máquina del tiempo de Bulma de Dragon Ball - 8 cm. El invento que cambió la historia.',
        palabrasClave: 'Dragon Ball, máquina del tiempo, Bulma, vehículo, viaje en el tiempo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_051.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_051_1.png'
    },
    {
        id: 'DB_VEH_052',
        sku: 'DB_VEH_052',
        nombre: 'Dragon Ball - Máquina del Tiempo de Cell',
        tamaño: '8 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Vehículo máquina del tiempo de Cell de Dragon Ball - 8 cm. La versión del bio-androide.',
        palabrasClave: 'Dragon Ball, máquina del tiempo, Cell, vehículo, viaje en el tiempo',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_052.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_052_1.png'
    },
    {
        id: 'DB_VEH_053',
        sku: 'DB_VEH_053',
        nombre: 'Dragon Ball - Nave Sayayin',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Nave sayayin de Dragon Ball - 8 cm. La icónica esfera de los guerreros Saiyan.',
        palabrasClave: 'Dragon Ball, nave, sayayin, vehículo, esfera Saiyan',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_053.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_053_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_053_1.png'
    },
    {
        id: 'DB_VEH_054',
        sku: 'DB_VEH_054',
        nombre: 'Dragon Ball - Nave Capsule Corp',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Nave de Cápsula Corp de Dragon Ball - 7 cm. El vehículo de la familia Brief.',
        palabrasClave: 'Dragon Ball, Cápsula Corp, nave, vehículo, Capsule Corp',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_054.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_054_1.png'
    },
    {
        id: 'DB_VEH_055',
        sku: 'DB_VEH_055',
        nombre: 'Dragon Ball - Nave Espacial',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Nave de Dragon Ball - 7 cm. Vehículo espacial coleccionable.',
        palabrasClave: 'Dragon Ball, nave, vehículo, nave espacial Dragon Ball',
        categoria: 'Dragon Ball',
        categoriaPadre: 'Dragon Ball',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/DB_VEH_055.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/DB_VEH_055_1.png'
    },

    // ============================================
    // NARUTO
    // ============================================
    {
        id: 'OP_SET_056',
        sku: 'OP_SET_056',
        nombre: 'Naruto - Set de 6 Figuras',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 30,
        precioInflado: 52.00,
        descripcion: 'Set de 6 figuras de Naruto - 8 cm. Colección con los personajes principales de Konoha.',
        palabrasClave: 'Naruto, set, 6 figuras, anime, colección, Naruto Shippuden',
        categoria: 'Naruto',
        categoriaPadre: 'Naruto',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/OP_SET_056.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/OP_SET_056_1.png'
    },
    {
        id: 'OP_SET_057',
        sku: 'OP_SET_057',
        nombre: 'Naruto - Set de 6 Figuras (Vol 2)',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 40,
        precioInflado: 56.00,
        descripcion: 'Set de 6 figuras de Naruto - 8 cm. Segunda colección con personajes del universo ninja.',
        palabrasClave: 'Naruto, set, 6 figuras, anime, Naruto Shippuden, Akatsuki',
        categoria: 'Naruto',
        categoriaPadre: 'Naruto',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_SET_057.png'
    },

    // ============================================
    // ONE PIECE (UNIFICADO)
    // ============================================
    {
        id: 'OP_FIG_058',
        sku: 'OP_FIG_058',
        nombre: 'One Piece - Monkey D. Luffy',
        tamaño: '17 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Monkey D. Luffy de One Piece - 17 cm. El futuro Rey de los Piratas en formato figura.',
        palabrasClave: 'One Piece, Luffy, Monkey D Luffy, figura, acción, sombrero de paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_058.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_058_1.png'
    },
    {
        id: 'OP_FIG_059',
        sku: 'OP_FIG_059',
        nombre: 'One Piece - Luffy Flowing Cherry',
        tamaño: '24 cm',
        precioOferta: 45,
        descuento: 20,
        precioInflado: 54.00,
        descripcion: 'Figura de Luffy Flowing Cherry de One Piece - 24 cm. Edición especial con temática de cerezos.',
        palabrasClave: 'One Piece, Luffy, Flowing Cherry, figura grande, edición especial',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_059.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_059_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_059_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_059_3.png'
    },
    {
        id: 'OP_FIG_060',
        sku: 'OP_FIG_060',
        nombre: 'One Piece - Luffy Dios del Sol Nika (Gear 5)',
        tamaño: '10 cm',
        precioOferta: 24,
        descuento: 30,
        precioInflado: 31.20,
        descripcion: 'Figura de Luffy Dios del Sol Nika de One Piece - 10 cm. La transformación definitiva del Gear 5.',
        palabrasClave: 'One Piece, Luffy, Nika, Gear 5, figura, Dios del Sol',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_060.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_060_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_060_2.png'
    },
    {
        id: 'OP_FIG_061',
        sku: 'OP_FIG_061',
        nombre: 'One Piece - Luffy y Shanks',
        tamaño: '16 cm',
        precioOferta: 40,
        descuento: 40,
        precioInflado: 56.00,
        descripcion: 'Figura de Luffy y Shanks de One Piece - 16 cm. El emotivo encuentro del sombrero de paja.',
        palabrasClave: 'One Piece, Luffy, Shanks, dupla, figura, sombrero de paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873657/OP_FIG_061_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061_3.png'
    },
    {
        id: 'OP_FIG_062',
        sku: 'OP_FIG_062',
        nombre: 'One Piece - Luffy con Rostro Intercambiable',
        tamaño: '28 cm',
        precioOferta: 59,
        descuento: 50,
        precioInflado: 88.50,
        descripcion: 'Figura de Luffy con rostro intercambiable de One Piece - 28 cm. Incluye diferentes expresiones faciales.',
        palabrasClave: 'One Piece, Luffy, rostro intercambiable, figura grande, edición deluxe',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873656/OP_FIG_062.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_062_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873622/OP_FIG_062_2.png'
    },
    {
        id: 'OP_FIG_063',
        sku: 'OP_FIG_063',
        nombre: 'One Piece - Monkey D. Luffy Gear 5',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Figura de Monkey D. Luffy Gear 5 de One Piece - 19 cm. La forma más poderosa del capitán.',
        palabrasClave: 'One Piece, Luffy, Gear 5, figura, Nika',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_063.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_063_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_063_2.png'
    },
    {
        id: 'OP_FIG_064',
        sku: 'OP_FIG_064',
        nombre: 'One Piece - Monkey D. Luffy (Versión Básica)',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 30,
        precioInflado: 39.00,
        descripcion: 'Figura de Luffy de One Piece - 12 cm. Versión básica del capitán de los Sombrero de Paja.',
        palabrasClave: 'One Piece, Luffy, figura, Monkey D Luffy, sombrero de paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064_2.png'
    },
    {
        id: 'OP_FIG_065',
        sku: 'OP_FIG_065',
        nombre: 'One Piece - Luffy Gear 5 Pose de Batalla',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Luffy Gear 5 pose de batalla de One Piece - 18 cm. Dinámica pose del despertar.',
        palabrasClave: 'One Piece, Luffy, Gear 5, batalla, figura, pose dinámica',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_065.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_065_1.png'
    },
    {
        id: 'OP_FIG_066',
        sku: 'OP_FIG_066',
        nombre: 'One Piece - Nami',
        tamaño: '19 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Nami de One Piece - 19 cm. La navegante de los Sombrero de Paja.',
        palabrasClave: 'One Piece, Nami, figura femenina, navegante, Sombrero de Paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873619/OP_FIG_066.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_066_1.png'
    },
    {
        id: 'OP_SET_067',
        sku: 'OP_SET_067',
        nombre: 'One Piece - Set de 6 Figuras',
        tamaño: '8 cm',
        precioOferta: 49,
        descuento: 20,
        precioInflado: 58.80,
        descripcion: 'Set de 6 figuras de One Piece - 8 cm. Colección de mini figuras de los personajes principales.',
        palabrasClave: 'One Piece, set, 6 figuras, mini figuras, Sombrero de Paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_SET_067.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_SET_067_1.png'
    },
    {
        id: 'OP_FIG_068',
        sku: 'OP_FIG_068',
        nombre: 'One Piece - Roronoa Zoro',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Zoro de One Piece - 12 cm. El espadachín de tres espadas.',
        palabrasClave: 'One Piece, Zoro, figura, espadas, Roronoa Zoro, espadachín',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_FIG_068.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_FIG_068_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_068_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_068_3.png'
    },
    {
        id: 'OP_FIG_069',
        sku: 'OP_FIG_069',
        nombre: 'One Piece - Sanji',
        tamaño: '12x15 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Sanji de One Piece - 12x15 cm. El cocinero de los Sombrero de Paja.',
        palabrasClave: 'One Piece, Sanji, figura, cocinero, Vinsmoke',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_069.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_069_1.png'
    },
    {
        id: 'OP_FIG_070',
        sku: 'OP_FIG_070',
        nombre: 'One Piece - Portgas D. Ace',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Figura de Ace de One Piece - 12 cm. El hermano de Luffy, usuario de la fruta Mera Mera.',
        palabrasClave: 'One Piece, Ace, figura, fuego, Portgas D Ace, hermano de Luffy',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_070.png'
    },
    {
        id: 'OP_VEH_071',
        sku: 'OP_VEH_071',
        nombre: 'One Piece - Barco Thousand Sunny',
        tamaño: '7x8 cm',
        precioOferta: 24,
        descuento: 20,
        precioInflado: 28.80,
        descripcion: 'Barco Thousand Sunny de One Piece - 7x8 cm. El emblemático barco de los Sombrero de Paja.',
        palabrasClave: 'One Piece, barco, Thousand Sunny, vehículo, Sombrero de Paja',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873581/OP_VEH_071.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_VEH_071_1.png'
    },
    {
        id: 'OP_VEH_072',
        sku: 'OP_VEH_072',
        nombre: 'One Piece - Barco Going Merry',
        tamaño: '7x8 cm',
        precioOferta: 24,
        descuento: 30,
        precioInflado: 31.20,
        descripcion: 'Barco Going Merry de One Piece - 7x8 cm. El primer barco de la tripulación.',
        palabrasClave: 'One Piece, barco, Going Merry, vehículo, barco legendario',
        categoria: 'One Piece',
        categoriaPadre: 'One Piece',
        subcategoria: 'Vehículos',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_VEH_072.png'
    },

    // ============================================
    // MARVEL Y DC (UNIFICADO)
    // ============================================
    {
        id: 'MV_FIG_073',
        sku: 'MV_FIG_073',
        nombre: 'Marvel - Iron Man',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Iron Man de Marvel - 12 cm. El genio multimillonario en su armadura.',
        palabrasClave: 'Marvel, Iron Man, figura, superhéroe, Tony Stark, Avengers',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_073_1.png'
    },
    {
        id: 'MV_FIG_074',
        sku: 'MV_FIG_074',
        nombre: 'Marvel - Capitán América',
        tamaño: '13 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Capitán América de Marvel - 13 cm. El primer vengador con su escudo.',
        palabrasClave: 'Marvel, Capitán América, figura, escudo, superhéroe, Steve Rogers',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_073_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_074_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_074_2.png'
    },
    {
        id: 'MV_FIG_075',
        sku: 'MV_FIG_075',
        nombre: 'Marvel - Spider-Man',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Spider-Man de Marvel - 12 cm. El héroe arácnido de Nueva York.',
        palabrasClave: 'Marvel, Spider Man, figura, trepamuros, Peter Parker, telaraña',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873536/MV_FIG_075.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_075_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_075_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873533/MV_FIG_075_3.png'
    },
    {
        id: 'MV_SET_076',
        sku: 'MV_SET_076',
        nombre: 'Marvel - Set 4 Spider-Man',
        tamaño: '6-8 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Set de 4 figuras de Spider-Man - 6 a 8 cm. Diferentes versiones del héroe arácnido.',
        palabrasClave: 'Marvel, Spider Man, set, 4 figuras, diferentes versiones',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873536/MV_FIG_075.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_2.png'
    },
    {
        id: 'MV_SET_077',
        sku: 'MV_SET_077',
        nombre: 'Marvel - Set 3 Figuras Deadpool',
        tamaño: 'Variable',
        precioOferta: 30,
        descuento: 30,
        precioInflado: 39.00,
        descripcion: 'Set de 3 figuras de Deadpool - tamaño variable. El mercenario bocón en diferentes poses.',
        palabrasClave: 'Marvel, Deadpool, set, 3 figuras, mercenario, Wade Wilson',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873533/MV_SET_077_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_077_2.png'
    },
    {
        id: 'MV_SET_078',
        sku: 'MV_SET_078',
        nombre: 'Marvel - Set 4 Figuras de Groot',
        tamaño: '5 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Set de 4 figuras de Groot - 5 cm. El adorable ser arbóreo en mini versiones.',
        palabrasClave: 'Marvel, Groot, set, 4 figuras, baby Groot, Guardianes de la Galaxia',
        categoria: 'Marvel',
        categoriaPadre: 'Marvel',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873489/MV_SET_078.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873825/MV_SET_078_1.png'
    },
    {
        id: 'MV_FIG_079',
        sku: 'MV_FIG_079',
        nombre: 'DC - Superman',
        tamaño: '15 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Superman de DC - 15 cm. El Hombre de Acero de Metrópolis.',
        palabrasClave: 'DC, Superman, figura, superhéroe, Clark Kent, Hombre de Acero',
        categoria: 'DC',
        categoriaPadre: 'DC',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_3.png'
    },

    // ============================================
    // POKEMON (UNIFICADO)
    // ============================================
    {
        id: 'PK_SET_080',
        sku: 'PK_SET_080',
        nombre: 'Pokémon - Set de 6 Figuras',
        tamaño: '6-7 cm',
        precioOferta: 59,
        descuento: 20,
        precioInflado: 70.80,
        descripcion: 'Set de 6 Pokémons - 6 a 7 cm. Colección de los Pokémon más populares.',
        palabrasClave: 'Pokémon, set, 6 figuras, miniaturas, Pikachu, Charizard',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/PK_SET_080.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_1.png , https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_4.png'
    },
    {
        id: 'PK_SET_081',
        sku: 'PK_SET_081',
        nombre: 'Pokémon - Set de 8 Figuras',
        tamaño: '4-5 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set de 8 Pokémons - 4 a 5 cm. Mini figuras de la primera generación.',
        palabrasClave: 'Pokémon, set, 8 figuras, mini, primera generación',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081_2.png'
    },
    {
        id: 'PK_SET_082',
        sku: 'PK_SET_082',
        nombre: 'Pokémon - Set de 5 Snorlax',
        tamaño: '3.5 cm',
        precioOferta: 30,
        descuento: 40,
        precioInflado: 42.00,
        descripcion: 'Set de 5 Snorlax - 3.5 cm. El Pokémon dormilón en diferentes poses.',
        palabrasClave: 'Pokémon, Snorlax, set, 5 figuras, dormilón',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_082.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_082_1.png'
    },
    {
        id: 'PK_SET_083',
        sku: 'PK_SET_083',
        nombre: 'Pokémon - Pokebola + 24 Pokémon',
        tamaño: '7x7 cm / 3 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Pokebola con 24 Pokémons - 7x7 cm y 3 cm. El set más completo de miniaturas.',
        palabrasClave: 'Pokémon, pokebola, set, 24 figuras, colección completa',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_083.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873479/PK_SET_083_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_SET_083_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873444/PK_SET_083_3.png'
    },
    {
        id: 'PK_LMP_084',
        sku: 'PK_LMP_084',
        nombre: 'Pokémon - Lámpara de Pikachu',
        tamaño: '13 cm',
        precioOferta: 28,
        descuento: 20,
        precioInflado: 33.60,
        descripcion: 'Lámpara de Pikachu - 13 cm. Luz nocturna LED del Pokémon más famoso.',
        palabrasClave: 'Pokémon, Pikachu, lámpara, luz nocturna, decoración, LED',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Lámparas',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_084.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_084_1.png'
    },
    {
        id: 'PK_LMP_085',
        sku: 'PK_LMP_085',
        nombre: 'Pokémon - Lámpara de Psyduck',
        tamaño: '10x8 cm',
        precioOferta: 28,
        descuento: 30,
        precioInflado: 36.40,
        descripcion: 'Lámpara de Psyduck - 10x8 cm. El Pokémon con dolor de cabeza en formato luz.',
        palabrasClave: 'Pokémon, Psyduck, lámpara, decoración, luz nocturna',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Lámparas',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_085.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_085_1.png'
    },
    {
        id: 'PK_LMP_086',
        sku: 'PK_LMP_086',
        nombre: 'Pokémon - Lámpara de Gengar',
        tamaño: '10x10 cm',
        precioOferta: 28,
        descuento: 40,
        precioInflado: 39.20,
        descripcion: 'Lámpara de Gengar - 10x10 cm. El Pokémon fantasma ilumina tu habitación.',
        palabrasClave: 'Pokémon, Gengar, lámpara, ambientador, luz, fantasma',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Lámparas',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_086.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_086_1.png'
    },
    {
        id: 'PK_FIG_087',
        sku: 'PK_FIG_087',
        nombre: 'Pokémon - Cubone',
        tamaño: '8 cm',
        precioOferta: 24,
        descuento: 50,
        precioInflado: 36.00,
        descripcion: 'Figura de Cubone de Pokémon - 8 cm. El Pokémon huérfano con su cráneo.',
        palabrasClave: 'Pokémon, Cubone, figura, huérfano, cráneo',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_4.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_2.png'
    },
    {
        id: 'PK_FIG_088',
        sku: 'PK_FIG_088',
        nombre: 'Pokémon - Bulbasaur con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Figura de Bulbasaur con almohada - 8 cm. El Pokémon semilla en modo descanso.',
        palabrasClave: 'Pokémon, Bulbasaur, almohada, figura, descanso',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_088.png'
    },
    {
        id: 'PK_FIG_089',
        sku: 'PK_FIG_089',
        nombre: 'Pokémon - Komala con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 30,
        precioInflado: 32.50,
        descripcion: 'Figura de Komala con almohada - 8 cm. El Pokémon koala siempre dormido.',
        palabrasClave: 'Pokémon, Komala, almohada, figura, koala',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_089.png'
    },
    {
        id: 'PK_FIG_090',
        sku: 'PK_FIG_090',
        nombre: 'Pokémon - Snorlax con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Figura de Snorlax con almohada - 8 cm. El Pokémon dormilón en versión mini.',
        palabrasClave: 'Pokémon, Snorlax, almohada, figura, dormilón',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_090.png'
    },
    {
        id: 'PK_FIG_091',
        sku: 'PK_FIG_091',
        nombre: 'Pokémon - Pikachu con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 50,
        precioInflado: 37.50,
        descripcion: 'Figura de Pikachu con almohada - 8 cm. El Pokémon ratón en modo descanso.',
        palabrasClave: 'Pokémon, Pikachu, almohada, figura, ratón eléctrico',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_091.png'
    },
    {
        id: 'PK_FIG_092',
        sku: 'PK_FIG_092',
        nombre: 'Pokémon - Eevee con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Figura de Eevee con almohada - 8 cm. El Pokémon evolución en modo relajado.',
        palabrasClave: 'Pokémon, Eevee, almohada, figura, evolución',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/PK_FIG_092.png'
    },
    {
        id: 'PK_FIG_093',
        sku: 'PK_FIG_093',
        nombre: 'Pokémon - Jirachi con Almohada',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 30,
        precioInflado: 32.50,
        descripcion: 'Figura de Jirachi con almohada - 8 cm. El Pokémon deseo en modo descanso.',
        palabrasClave: 'Pokémon, Jirachi, almohada, figura, deseo, legendario',
        categoria: 'Pokemon',
        categoriaPadre: 'Pokemon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/PK_FIG_093.png'
    },

    // ============================================
    // DEMON SLAYER
    // ============================================
    {
        id: 'DS_SET_094',
        sku: 'DS_SET_094',
        nombre: 'Demon Slayer - Set de 15 Figuras',
        tamaño: '5 cm',
        precioOferta: 99,
        descuento: 40,
        precioInflado: 138.60,
        descripcion: 'Set de 15 figuras de Demon Slayer - 5 cm. La colección completa de Kimetsu no Yaiba.',
        palabrasClave: 'Demon Slayer, Kimetsu no Yaiba, set, 15 figuras, colección completa',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_094.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_094_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_094_2.png'
    },
    {
        id: 'DS_SET_095',
        sku: 'DS_SET_095',
        nombre: 'Demon Slayer - Set de 6 Figuras',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 50,
        precioInflado: 60.00,
        descripcion: 'Set de 6 figuras de Demon Slayer - 8 cm. Los principales cazadores de demonios.',
        palabrasClave: 'Demon Slayer, set, 6 figuras, mini, Kimetsu no Yaiba',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/DS_SET_095.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_095_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_095_1.png'
    },
    {
        id: 'DS_FIG_096',
        sku: 'DS_FIG_096',
        nombre: 'Demon Slayer - Tanjiro Kamado',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Tanjiro Kamado de Demon Slayer - 16 cm. El protagonista con su icónica espada.',
        palabrasClave: 'Demon Slayer, Tanjiro, figura, acción, Kimetsu no Yaiba, respiración del agua',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_SET_096.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_096_1.png'
    },
    {
        id: 'DS_FIG_097',
        sku: 'DS_FIG_097',
        nombre: 'Demon Slayer - Nezuko Kamado',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Nezuko Kamado de Demon Slayer - 16 cm. La hermana demonio de Tanjiro.',
        palabrasClave: 'Demon Slayer, Nezuko, figura, bambú, Kimetsu no Yaiba, demonio',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_FIG_097.png'
    },
    {
        id: 'DS_FIG_098',
        sku: 'DS_FIG_098',
        nombre: 'Demon Slayer - Vibration Stars Nezuko Kamado',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 40,
        precioInflado: 54.60,
        descripcion: 'Figura Vibration Stars de Nezuko de Demon Slayer - 19 cm. Edición especial con pose dinámica.',
        palabrasClave: 'Demon Slayer, Nezuko, Vibration Stars, figura, edición especial',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_FIG_098.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873386/DS_FIG_098_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_098_2.png'
    },
    {
        id: 'DS_FIG_099',
        sku: 'DS_FIG_099',
        nombre: 'Demon Slayer - Shinobu Kocho',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Shinobu Kocho de Demon Slayer - 16 cm. La pilar insecto con su espada.',
        palabrasClave: 'Demon Slayer, Shinobu, figura, insecto, pilar, Kocho',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873353/DS_FIG_099.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_3.png'
    },
    {
        id: 'DS_FIG_100',
        sku: 'DS_FIG_100',
        nombre: 'Demon Slayer - Obanai Iguro',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Obanai Iguro de Demon Slayer - 16 cm. El pilar serpiente con su mascota.',
        palabrasClave: 'Demon Slayer, Obanai, figura, serpiente, pilar, Iguro',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100_1.png'
    },
    {
        id: 'DS_FIG_101',
        sku: 'DS_FIG_101',
        nombre: 'Demon Slayer - Inosuke Hashibira',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Inosuke Hashibira de Demon Slayer - 16 cm. El cazador con máscara de jabalí.',
        palabrasClave: 'Demon Slayer, Inosuke, figura, máscara, jabalí, Hashibira',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_101.png'
    },
    {
        id: 'DS_FIG_102',
        sku: 'DS_FIG_102',
        nombre: 'Demon Slayer - Akaza',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Akaza de Demon Slayer - 16 cm. El poderoso demonio de la luna superior.',
        palabrasClave: 'Demon Slayer, Akaza, figura, demonio, luna superior, Kimetsu',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_102.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_102_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_102_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_102_1.png'
    },
    {
        id: 'DS_FIG_103',
        sku: 'DS_FIG_103',
        nombre: 'Demon Slayer - Muzan Kibutsuji',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Muzan Kibutsuji de Demon Slayer - 16 cm. El rey de los demonios.',
        palabrasClave: 'Demon Slayer, Muzan, figura, rey demonio, Kibutsuji, Kimetsu',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873314/DS_FIG_103_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_103_1.png'
    },
    {
        id: 'DS_FIG_104',
        sku: 'DS_FIG_104',
        nombre: 'Demon Slayer - Zenitsu Agatsuma',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Zenitsu Agatsuma de Demon Slayer - 16 cm. El cazador del rayo.',
        palabrasClave: 'Demon Slayer, Zenitsu, figura, rayo, Agatsuma, Kimetsu',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_104.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_104_1.png'
    },
    {
        id: 'DS_FIG_105',
        sku: 'DS_FIG_105',
        nombre: 'Demon Slayer - Mitsuri Kanroji',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Mitsuri Kanroji de Demon Slayer - 16 cm. La pilar del amor.',
        palabrasClave: 'Demon Slayer, Mitsuri, figura, amor, pilar, Kanroji',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_105_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105_1.png'
    },
    {
        id: 'DS_FIG_106',
        sku: 'DS_FIG_106',
        nombre: 'Demon Slayer - Giyu Tomioka',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Giyu Tomioka de Demon Slayer - 16 cm. El pilar del agua.',
        palabrasClave: 'Demon Slayer, Giyu, figura, agua, pilar, Tomioka',
        categoria: 'Demon Slayer',
        categoriaPadre: 'Demon Slayer',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106_1.png'
    },

    // ============================================
    // VARIOS (BTS, Digimon, Bob Esponja, etc.)
    // ============================================
    {
        id: 'BT_SET_107',
        sku: 'BT_SET_107',
        nombre: 'BTS - Set de 7 Figuras',
        tamaño: '8 cm',
        precioOferta: 65,
        descuento: 50,
        precioInflado: 97.50,
        descripcion: 'Set de 7 figuras de BTS - 8 cm. Los integrantes del grupo de K-Pop más famoso.',
        palabrasClave: 'BTS, k-pop, set, 7 figuras, idol, RM, Jin, SUGA, j-hope, Jimin, V, Jungkook',
        categoria: 'BTS',
        categoriaPadre: 'BTS',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/BT_SET_107.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/BT_SET_107_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873311/BT_SET_107_2.png'
    },
    {
        id: 'DG_SET_108',
        sku: 'DG_SET_108',
        nombre: 'Digimon - Set de 9 Figuras',
        tamaño: '4-5 cm',
        precioOferta: 40,
        descuento: 20,
        precioInflado: 48.00,
        descripcion: 'Set de 9 figuras de Digimon - 4 a 5 cm. Los mejores amigos digitales.',
        palabrasClave: 'Digimon, set, 9 figuras, mini, Agumon, Gabumon',
        categoria: 'Digimon',
        categoriaPadre: 'Digimon',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874449/DG_SET_108.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872604/DG_SET_108_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873204/DG_SET_108_1.png'
    },
    {
        id: 'SB_SET_109',
        sku: 'SB_SET_109',
        nombre: 'Bob Esponja - Set de 6 Figuras',
        tamaño: 'Variable',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Set de 6 figuras de Bob Esponja - tamaño variable. Los habitantes de Fondo de Bikini.',
        palabrasClave: 'Bob Esponja, SpongeBob, set, 6 figuras, Patricio, Arenita, Calamardo',
        categoria: 'Bob Esponja',
        categoriaPadre: 'Bob Esponja',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872583/SB_SET_109.png'
    },
    {
        id: 'SM_SET_110',
        sku: 'SM_SET_110',
        nombre: 'Super Mario - Set de 6 Figuras',
        tamaño: '4-6 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set de 6 figuras de Super Mario Bros - 4 a 6 cm. Los personajes del Reino Champiñón.',
        palabrasClave: 'Super Mario, Mario Bros, set, 6 figuras, Nintendo, Luigi, Peach, Bowser',
        categoria: 'Super Mario',
        categoriaPadre: 'Super Mario',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872560/SM_SET_110.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/SM_SET_110_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/SM_SET_110_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/SM_SET_110_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/SM_SET_110_4.png'
    },
    {
        id: 'MM_SET_111',
        sku: 'MM_SET_111',
        nombre: 'Mickey Mouse - Set de 6 Figuras',
        tamaño: '6 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set de 6 figuras de Mickey Mouse - 6 cm. Los personajes clásicos de Disney.',
        palabrasClave: 'Mickey Mouse, Disney, set, 6 figuras, Minnie, Donald, Goofy',
        categoria: 'Mickey Mouse',
        categoriaPadre: 'Mickey Mouse',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/MM_SET_111.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/MM_SET_111_1.png'
    },
    {
        id: 'YG_FIG_112',
        sku: 'YG_FIG_112',
        nombre: 'Yu-Gi-Oh! - Yugi Muto',
        tamaño: '13 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Yu-Gi-Oh! - 13 cm. El rey de los juegos.',
        palabrasClave: 'Yu-Gi-Oh!, figura, anime, Yugi, cartas, duelista',
        categoria: 'Yu-Gi-Oh!',
        categoriaPadre: 'Yu-Gi-Oh!',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/YG_FIG_112.png'
    },
    {
        id: 'TS_SET_113',
        sku: 'TS_SET_113',
        nombre: 'Toy Story - Set de 8 Figuras',
        tamaño: '4-5 cm',
        precioOferta: 40,
        descuento: 20,
        precioInflado: 48.00,
        descripcion: 'Set de 8 figuras de Toy Story - 4 a 5 cm. Los juguetes de Andy.',
        palabrasClave: 'Toy Story, Disney, set, 8 figuras, mini, Woody, Buzz Lightyear',
        categoria: 'Toy Story',
        categoriaPadre: 'Toy Story',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/TS_SET_113.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/TS_SET_113_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/TS_SET_113_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/TS_SET_113_3.png'
    },
    {
        id: 'HR_SET_114',
        sku: 'HR_SET_114',
        nombre: 'Terror - Set de 10 Figuras de Películas de Terror',
        tamaño: '5 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 10 figuras de películas de terror - 5 cm. Los íconos del horror.',
        palabrasClave: 'Terror, horror, set, 10 figuras, Freddy, Jason, Michael Myers, Chucky',
        categoria: 'Terror',
        categoriaPadre: 'Terror',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HR_SET_114.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HR_SET_114_1.png'
    },
    {
        id: 'HK_SET_115',
        sku: 'HK_SET_115',
        nombre: 'Hello Kitty - Set de 8 Figuras',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Set de 8 figuras de Hello Kitty - 8 cm. La gatita más famosa de Sanrio.',
        palabrasClave: 'Hello Kitty, Sanrio, set, 8 figuras, kawaii',
        categoria: 'Hello Kitty',
        categoriaPadre: 'Hello Kitty',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HK_SET_115.png'
    },
    {
        id: 'LS_SET_116',
        sku: 'LS_SET_116',
        nombre: 'Lilo y Stitch - Set de 6 Figuras',
        tamaño: '2 cm',
        precioOferta: 25,
        descuento: 50,
        precioInflado: 37.50,
        descripcion: 'Set de 6 figuras de Lilo y Stitch - 2 cm. Miniaturas de la familia de Stitch.',
        palabrasClave: 'Lilo y Stitch, Disney, set, 6 figuras, mini, experimento 626',
        categoria: 'Lilo y Stitch',
        categoriaPadre: 'Lilo y Stitch',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872501/LS_SET_116.png'
    },
    {
        id: 'LS_SET_117',
        sku: 'LS_SET_117',
        nombre: 'Lilo y Stitch - Set de 12 Figuras',
        tamaño: '2-3 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Set de 12 figuras de Lilo y Stitch - 2 a 3 cm. La colección completa de experimentos.',
        palabrasClave: 'Lilo y Stitch, set, 12 figuras, miniaturas, experimentos, Disney',
        categoria: 'Lilo y Stitch',
        categoriaPadre: 'Lilo y Stitch',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/LS_SET_117.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872471/LS_SET_117_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872452/LS_SET_117_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872433/LS_SET_117_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/LS_SET_117_4.png'
    },
    {
        id: 'DN_FIG_118',
        sku: 'DN_FIG_118',
        nombre: 'Death Note - Ryuk',
        tamaño: '24 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Figura de Ryuk de Death Note - 24 cm. El shinigami amante de las manzanas.',
        palabrasClave: 'Death Note, Ryuk, figura, shinigami, dios de la muerte',
        categoria: 'Death Note',
        categoriaPadre: 'Death Note',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/DN_FIG_118.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/DN_FIG_118_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_4.png'
    },
    {
        id: 'SW_FIG_119',
        sku: 'SW_FIG_119',
        nombre: 'Star Wars - Darth Vader Articulable',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 40,
        precioInflado: 42.00,
        descripcion: 'Figura articulable de Darth Vader de Star Wars - 10 cm. El Lord Sith articulado.',
        palabrasClave: 'Star Wars, Darth Vader, figura, articulable, Imperio Galáctico',
        categoria: 'Star Wars',
        categoriaPadre: 'Star Wars',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119_3.png'
    },
    {
        id: 'SM_FIG_120',
        sku: 'SM_FIG_120',
        nombre: 'Sailor Moon - Usagi Tsukino',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Sailor Moon - 16 cm. La guerrera lunar en acción.',
        palabrasClave: 'Sailor Moon, figura, anime, magical girl, Usagi, Tsukino',
        categoria: 'Sailor Moon',
        categoriaPadre: 'Sailor Moon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SM_FIG_120.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SM_FIG_120_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_120_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_120_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872403/SM_FIG_120_4.png'
    },
    {
        id: 'SM_FIG_121',
        sku: 'SM_FIG_121',
        nombre: 'Sailor Moon - Sailor Moon (Versión 2)',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Sailor Moon - 16 cm. Segunda versión de la guerrera lunar.',
        palabrasClave: 'Sailor Moon, figura, colección, anime, magical girl',
        categoria: 'Sailor Moon',
        categoriaPadre: 'Sailor Moon',
        subcategoria: 'Figuras',
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_121.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872403/SM_FIG_121_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_121_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/SM_FIG_121_3.png'
    },
    {
        id: 'SF_SET_122',
        sku: 'SF_SET_122',
        nombre: 'Street Fighter - Set de Figuras',
        tamaño: '9 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Set de figuras de Street Fighter - 9 cm. Los luchadores más famosos.',
        palabrasClave: 'Street Fighter, set, figuras, Ryu, Chun-Li, Ken, Akuma',
        categoria: 'Street Fighter',
        categoriaPadre: 'Street Fighter',
        subcategoria: 'Sets',
        esSet: true,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872402/SF_SET_122_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872360/SF_SET_122_2.png'
    }
];

// ============================================
// FUNCIONES DE UTILIDAD OPTIMIZADAS
// ============================================

// Obtener categorías principales (sin duplicados)
function obtenerCategoriasPrincipales() {
    const categorias = [...new Set(productos.map(p => p.categoriaPadre || p.categoria))];
    return categorias.sort();
}

// Obtener subcategorías de una categoría principal
function obtenerSubcategorias(categoriaPadre) {
    const subcategorias = [...new Set(productos
        .filter(p => (p.categoriaPadre || p.categoria) === categoriaPadre)
        .map(p => p.subcategoria || 'General'))];
    return subcategorias.sort();
}

// Obtener productos por categoría principal
function obtenerProductosPorCategoria(categoria) {
    if (categoria === 'todos') return productos;
    return productos.filter(p => (p.categoriaPadre || p.categoria) === categoria);
}

// Obtener productos por subcategoría
function obtenerProductosPorSubcategoria(categoriaPadre, subcategoria) {
    return productos.filter(p => 
        (p.categoriaPadre || p.categoria) === categoriaPadre && 
        (p.subcategoria || 'General') === subcategoria
    );
}

// Buscar productos
function buscarProductos(termino) {
    const busqueda = termino.toLowerCase();
    return productos.filter(p => 
        p.nombre.toLowerCase().includes(busqueda) ||
        p.sku.toLowerCase().includes(busqueda) ||
        (p.categoriaPadre || p.categoria).toLowerCase().includes(busqueda) ||
        p.palabrasClave.toLowerCase().includes(busqueda) ||
        (p.subcategoria && p.subcategoria.toLowerCase().includes(busqueda))
    );
}

// Función legacy para compatibilidad
function obtenerCategorias() {
    return obtenerCategoriasPrincipales();
}

// Exportar para usar en otros archivos
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { 
        productos, 
        obtenerCategorias,
        obtenerCategoriasPrincipales,
        obtenerSubcategorias,
        obtenerProductosPorCategoria,
        obtenerProductosPorSubcategoria,
        buscarProductos
    };
}